# common configuration for both dev and prod
version: "3"
# container is synonymous to service
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    # makes sure that mongo container is started first
    # but doesn't consider if mongo db is up and running
    # need to manually write logic to handle this scenario
    # mongoose keeps trying to connect every 30 seconds out of the box in this instance though
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=samyak
    # named volume to retain db data after container is down
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

# declaring a named volume
volumes:
  mongo-db:
