version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      #Location of the docker file
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASSWORD=samyak
      - SESSION_SECRET=secret

    command: npm run dev
