version: "3"
services:
  node-app:
    build:
      #Location of the docker file
      context: . 
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
