version: "3"
services:
  nginx:
    ports:
      - "80:80"

  node-app:
    build:
      #Location of the docker file
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node index.js
