version: "3"
services:
  node-app:
    build:
      #Location of the docker file
      context: . 
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm index.js
